name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
      with:
        node-version: '20.8'
    - name: Install Dependencies
      run: npm install
    - name: Build the project
      run: npm run build 
    - name: Test the project
      run: NODE_ENV=test npm run test
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 --tag ${{ secrets.DOCKER_USERNAME }}/group-scheduler-backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/group-scheduler-backend:latest
    